### PR TITLE
Push skeleton

### PR DESCRIPTION
**Pull request by pboothe**
The skeleton of the pusher, with one working unit test

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/pusher/2)

### CODE REVIEW

**Comment by pboothe** [comment]
Requesting early feedback on `CreateTarfile` and its associated unit test `TestCreateTarfile`

**Comment by stephen-soltesz** [comment]
I've added some thoughts for `CreateTarfile` and its associated unit test `TestCreateTarfile`.

I like the shape of both functions. I lean on the side of more integration-like tests anyway and I've found it often painfully impractical to create pure unit tests with Go. So this approach lgtm.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[pusher.go, line 110 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjUPTvt2nZTDmRp-Ga:-KxjUPTw4R2c89VKcnoA:bel6dy3) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher.go#L110)):*
> ```Go
> 
> 
> // Exported for test purposes only
> ```

What do you want the public interface of the pusher package to be?

Go supports both types of tests at the same time. So if you want to create a file named `foo_test.go` with the package `pusher`, you can test this function without using the public interface.

---

*[pusher.go, line 111 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjVmB33Ju2sSDd5W5k:-KxjVmB4ec3wVMnxGwRi:b-ixn6n2) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher.go#L111)):*
> ```Go
> 
> // Exported for test purposes only
> func CreateTarfile(files []*LocalDataFile) (error, *bytes.Buffer) {
> ```

While I can't recall ever seeing this written, it's much more common for the `error` type to be returned second and the primary type first.

This shows up in the calling convention that often looks like:

```
val, err := CreateTarfile(...)
if err != nil {
}
```

`val` is the thing we really care about. See the standard Go libraries for numerous examples with that ordering.

---

*[pusher.go, line 113 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjV4sY-tEgbizkvqaM:-KxjV4sY-tEgbizkvqaN:b-yr58vp) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher.go#L113)):*
> ```Go
> func CreateTarfile(files []*LocalDataFile) (error, *bytes.Buffer) {
> 	buffer := new(bytes.Buffer)
>         gzipWriter := gzip.NewWriter(buffer)
> ```

`gofmt`!

---

*[pusher_test.go, line 36 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjYRkkeUjycgBdlIKg:-KxjYRkkeUjycgBdlIKh:b-r9zwjz) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher_test.go#L36)):*
> ```Go
> 	defer os.Chdir(currdir)
> 	defer os.RemoveAll(tempdir)
> 	file1, _ := os.Create("file1.txt")
> ```

I know this is a lot of boiler plate, but we want to test `err`. Maybe this could be a simple help function?

---

*[pusher_test.go, line 44 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjZ0rKR-t87bS9mUgm:-KxjZ0rKR-t87bS9mUgn:b-pksn4r) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher_test.go#L44)):*
> ```Go
> 	_ = file2.Sync()
> 	f2info, _ := file2.Stat()
> 	fileList := make([]*pusher.LocalDataFile, 2)
> ```

It's kind of six-one / half-dozen the other, but this looks like a candidate for an inline struct definition:

```
fileList := []*pusherLocalDataFile{
 	&pusher.LocalDataFile{
 		FullRelativeName: "file1.txt",
 		Info: f1info,
 		CachedSize: 12,
 	},
 	&pusher.LocalDataFile{
 		FullRelativeName: "file2.txt",
 		Info: f2info,
 		CachedSize: 14,
 	},
}
```

I do this when I can especially in tests. I think I may have changed type definitions to make it easier to do this for tests. My thinking being it would also make it easier to use in other contexts too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/pusher/2#-:-Kxj_P9l5o2LBnUJMJxv:b2izm2b)*

**Comment by pboothe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[pusher.go, line 110 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjUPTvt2nZTDmRp-Ga:-Kxmf9aHKUoju2WDm1ar:b-7mfjxw) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher.go#L110)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What do you want the public interface of the pusher package to be?

Go supports both types of tests at the same time. So if you want to create a file named `foo_test.go` with the package `pusher`, you can test this function without using the public interface.
</blockquote></details>

Given that I am testing internals, I'll use the `parser` package. I know that Greg prefers `parser_test`, but exporting all the internals just seems like asking for trouble.

---

*[pusher.go, line 111 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjVmB33Ju2sSDd5W5k:-KxmeoP8UNUBvAdo6JG8:bc7qgsj) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher.go#L111)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

While I can't recall ever seeing this written, it's much more common for the `error` type to be returned second and the primary type first.

This shows up in the calling convention that often looks like:

```
val, err := CreateTarfile(...)
if err != nil {
}
```

`val` is the thing we really care about. See the standard Go libraries for numerous examples with that ordering.
</blockquote></details>

Thanks!  This is exactly the kind of thing that this review was for :)

---

*[pusher.go, line 113 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjV4sY-tEgbizkvqaM:-Kxmenbs2Vp-WW0f4W_Y:b-896fix) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`gofmt`!
</blockquote></details>

Done.

---

*[pusher_test.go, line 36 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjYRkkeUjycgBdlIKg:-KxmvUY7GLNsXKGSNJ1U:b-896fix) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher_test.go#L36)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I know this is a lot of boiler plate, but we want to test `err`. Maybe this could be a simple help function?
</blockquote></details>

Done.

---

*[pusher_test.go, line 44 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjZ0rKR-t87bS9mUgm:-KxmfdpUhOBhd5EvKiKh:b-ucfknh) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher_test.go#L44)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It's kind of six-one / half-dozen the other, but this looks like a candidate for an inline struct definition:

```
fileList := []*pusherLocalDataFile{
 	&pusher.LocalDataFile{
 		FullRelativeName: "file1.txt",
 		Info: f1info,
 		CachedSize: 12,
 	},
 	&pusher.LocalDataFile{
 		FullRelativeName: "file2.txt",
 		Info: f2info,
 		CachedSize: 14,
 	},
}
```

I do this when I can especially in tests. I think I may have changed type definitions to make it easier to do this for tests. My thinking being it would also make it easier to use in other contexts too.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/pusher/2)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pusher_test.go, line 44 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjZ0rKR-t87bS9mUgm:-Kxn1f2XQH_S_71lo1ub:b2r6mkk) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher_test.go#L44)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

And, maybe phrased differently. I have felt frustration using other libraries that defined types that made it more difficult to define instances for tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/pusher/2)*

**Comment by pboothe** [comment]
PTAL

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[pusher.go, line 37 at r2](https://reviewable.io:443/reviews/m-lab/pusher/2#-Kxs6amCxIZZsNsYgspE:-Kxs6amCxIZZsNsYgspF:b-614gkb) ([raw file](https://github.com/m-lab/pusher/blob/af9a2c55c76f71bcd2c5cda0e9e610fdc190497b/pusher.go#L37)):*
> ```Go
> // files it contains.  To prevent the possibility of name collisions, send
> // files down the channel in ascending order by mtime.  To terminate the
> // Uploader, send a nil down the channel as a signal final value which will
> ```

My original thought: you probably should close the channel, rather than sending a nil.  But reading more of the PR, it seems that the channel may not be closed.

If the intent is to close the channel, I think you should just close the channel from the sender side.  If the intent is for this to be a marker to indicate that the tar file should be closed and uploaded, then I have to think about it more.  I prefer the former option.

My natural way of thinking of this is that, at any time, you have a single tar file constructor receiving filenames on the channel, compressing them and writing them to the tar file.  So if anytime you want to close and upload, you signal that by closing the channel, opening a new channel, and passing it to a new tar uploader object.

Now I'm thinking about the chain of channel connected things, vs an object that you make successive AddFile method calls on, and eventually call Upload and DeleteFiles.  What are your thoughts on pros/cons of making this asynchronous and/or driven by channels?

---

*[pusher.go, line 69 at r2](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxsdqCf_EWDDWhzjAet:-KxsdqCghfv7mrCdLFiG:bamynjj) ([raw file](https://github.com/m-lab/pusher/blob/af9a2c55c76f71bcd2c5cda0e9e610fdc190497b/pusher.go#L69)):*
> ```Go
> }
> 
> // bufferThenProcess receives files on the inputChannel, and then, when the
> ```

What is the motivation for buffering file names, rather than incrementally building the tar object?  Probably should have discussion of this at the top of the file, possibly as part of the package description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/pusher/2)*

**Comment by pboothe** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[pusher.go, line 37 at r2](https://reviewable.io:443/reviews/m-lab/pusher/2#-Kxs6amCxIZZsNsYgspE:-KxslHwAtza7WXRb3eiQ:b2mur1i) ([raw file](https://github.com/m-lab/pusher/blob/af9a2c55c76f71bcd2c5cda0e9e610fdc190497b/pusher.go#L37)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

My original thought: you probably should close the channel, rather than sending a nil.  But reading more of the PR, it seems that the channel may not be closed.

If the intent is to close the channel, I think you should just close the channel from the sender side.  If the intent is for this to be a marker to indicate that the tar file should be closed and uploaded, then I have to think about it more.  I prefer the former option.

My natural way of thinking of this is that, at any time, you have a single tar file constructor receiving filenames on the channel, compressing them and writing them to the tar file.  So if anytime you want to close and upload, you signal that by closing the channel, opening a new channel, and passing it to a new tar uploader object.

Now I'm thinking about the chain of channel connected things, vs an object that you make successive AddFile method calls on, and eventually call Upload and DeleteFiles.  What are your thoughts on pros/cons of making this asynchronous and/or driven by channels?

</blockquote></details>

I think the external interface being a channel is a very good idea. I really like the entirety of the library interface consisting of "the struct you send down the channel", "the setup the channel function", and "the channel", with all other complication hidden from the library user.

The "nil" thing is just a consequence of not enough go experience on my part. The right thing, now that I know a little more, is to respond appropriately to a channel close event.

Making pipes the foundation of the internal organization of the module is much more optional, but I think in pipes pretty naturally after too many years of bash.   I definitely don't want the external user to have to  know anything about when the upload occurs, and I would strongly prefer the channel to be unidirectional. But having the internal organization of the function cause channels to be deleted and created might be the right thing? It sounds more complicated to me, though.  One goroutine, reading files, uploading when the tarfile gets too big or too old: that sounds like the recipe for success from my perspective.

---

*[pusher.go, line 69 at r2](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxsdqCf_EWDDWhzjAet:-KxspT83UqGiSwD8sbPV:b1j9dyt) ([raw file](https://github.com/m-lab/pusher/blob/af9a2c55c76f71bcd2c5cda0e9e610fdc190497b/pusher.go#L69)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

What is the motivation for buffering file names, rather than incrementally building the tar object?  Probably should have discussion of this at the top of the file, possibly as part of the package description.
</blockquote></details>

Scraper thinking, where tarfile creation used the "tar" command which created the tarfile in a big-bang process. I would happily change it to build the tarfile incrementally.

---

*[pusher_test.go, line 44 at r1](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxjZ0rKR-t87bS9mUgm:-KxsyN97N1D2Oa9Z5QKw:b-jipdkj) ([raw file](https://github.com/m-lab/pusher/blob/2087af0bdbb52b1282a1b840f697451c84b1cd60/pusher_test.go#L44)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

And, maybe phrased differently. I have felt frustration using other libraries that defined types that made it more difficult to define instances for tests.
</blockquote></details>

I always prefer literals when I can use them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/pusher/2)*

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[pusher.go, line 69 at r2](https://reviewable.io:443/reviews/m-lab/pusher/2#-KxsdqCf_EWDDWhzjAet:-KxtEj0uL1o2mVjIyTn4:b6wuxsk) ([raw file](https://github.com/m-lab/pusher/blob/af9a2c55c76f71bcd2c5cda0e9e610fdc190497b/pusher.go#L69)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Scraper thinking, where tarfile creation used the "tar" command which created the tarfile in a big-bang process. I would happily change it to build the tarfile incrementally.
</blockquote></details>

I think that will be a cleaner design.  So the "all at once" goes away then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/pusher/2)*

**Pull request closed without merging**
